return require("packer").startup(function()
	-- Packer can manage itself
	use("wbthomason/packer.nvim")
	use("neovim/nvim-lspconfig")
	use("hrsh7th/nvim-cmp")
	use("hrsh7th/cmp-path")
	use("hrsh7th/cmp-buffer")
	use("hrsh7th/cmp-nvim-lsp")
	use({
		"nvim-telescope/telescope.nvim",
		requires = { "nvim-lua/popup.nvim", "nvim-lua/plenary.nvim" },
	})
	use("L3MON4D3/LuaSnip")
	use("hoob3rt/lualine.nvim")
	use("andweeb/presence.nvim")
	use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
	use("gruvbox-community/gruvbox")
	use("b3nj5m1n/kommentary")
	use("editorconfig/editorconfig-vim")
	use("mfussenegger/nvim-dap")
	use({ "rcarriga/nvim-dap-ui", requires = { "mfussenegger/nvim-dap" } })
	use("georgewitteman/vim-fish")
	use("kyazdani42/nvim-web-devicons")
	use({ "tamago324/lir.nvim", requires = { "nvim-lua/plenary.nvim" } })
	use("folke/trouble.nvim")
	use("lukas-reineke/indent-blankline.nvim")
	use("nacro90/numb.nvim")
	use("windwp/nvim-autopairs")
	use("RRethy/nvim-treesitter-textsubjects")
	use("nvim-treesitter/playground")
end)
